version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lyd
    ports:
      - '5432:5432'
      
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
      
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
